/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import interfaces.Client;
import interfaces.IChatServer;
import java.net.UnknownHostException;
import java.rmi.AlreadyBoundException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Jorge Osvaldo perez Mendoza
 */
public class ChatView extends javax.swing.JFrame {
    private static String IP;    
    private static int PORT;
    public ArrayList<Client> listUsers;
    private ServerClient clServer;
    private IChatServer SERVER;
    private ArrayList<Client> ListUsers;
    private Integer ClientPORT;
    
    /**
     * Creates new form ChatView
     */
    public ChatView() {
        initComponents();
        pnlMain.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pnlServer = new javax.swing.JPanel();
        lblServer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtServerName = new javax.swing.JTextField();
        txtIP_Port1 = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        lblClientPort = new javax.swing.JLabel();
        txtPortClient = new javax.swing.JTextField();
        pnlLog = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        pnlMain = new javax.swing.JPanel();
        pnlusers = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlListUsers = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        LiUsers = new javax.swing.JList<>();
        pnlPrivado = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMsgPrivados = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPrivate = new javax.swing.JTextArea();
        btnSendPrivate = new javax.swing.JButton();
        txtUserSelec = new javax.swing.JLabel();
        pnlMsgGrupal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMsgGrupo = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(194, 216, 194));
        pnlHeader.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlTitle.setBackground(pnlHeader.getBackground());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Chat RMI");

        txtUserName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserName.setText("User01");
        txtUserName.setToolTipText("Usuario");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nombre de Usuario");

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addGroup(pnlTitleLayout.createSequentialGroup()
                        .addGroup(pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlServer.setBackground(pnlHeader.getBackground());

        lblServer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblServer.setText("Informacion del Servidor");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("IP y Puerto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nombre del Servidor");

        txtServerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtServerName.setText("ChatServe");
        txtServerName.setToolTipText("IP y Puerto");

        txtIP_Port1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIP_Port1.setText("172.30.80.1:1234");
        txtIP_Port1.setToolTipText("IP y Puerto");

        javax.swing.GroupLayout pnlServerLayout = new javax.swing.GroupLayout(pnlServer);
        pnlServer.setLayout(pnlServerLayout);
        pnlServerLayout.setHorizontalGroup(
            pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServerLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72))
                    .addGroup(pnlServerLayout.createSequentialGroup()
                        .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServer)
                            .addGroup(pnlServerLayout.createSequentialGroup()
                                .addComponent(txtIP_Port1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtServerName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        pnlServerLayout.setVerticalGroup(
            pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIP_Port1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(txtServerName))
                .addContainerGap())
        );

        btnStart.setBackground(new java.awt.Color(0, 204, 255));
        btnStart.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("Inicar");
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });

        lblClientPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblClientPort.setForeground(new java.awt.Color(255, 255, 255));
        lblClientPort.setText("Puerto del Cliente");

        txtPortClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPortClient.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPortClient.setText("4321");
        txtPortClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnStart)
                        .addGap(125, 125, 125))
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblClientPort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPortClient, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)))
                .addComponent(pnlServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(pnlServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClientPort)
                    .addComponent(txtPortClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addContainerGap())
        );

        txtLog.setBackground(new java.awt.Color(204, 204, 204));
        txtLog.setColumns(20);
        txtLog.setRows(5);
        txtLog.setEnabled(false);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuarios");
        jLabel3.setToolTipText("");

        pnlListUsers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LiUsers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LiUsers.setForeground(new java.awt.Color(0, 153, 153));
        LiUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LiUsers.setToolTipText("");
        LiUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LiUsersValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(LiUsers);
        LiUsers.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout pnlListUsersLayout = new javax.swing.GroupLayout(pnlListUsers);
        pnlListUsers.setLayout(pnlListUsersLayout);
        pnlListUsersLayout.setHorizontalGroup(
            pnlListUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlListUsersLayout.setVerticalGroup(
            pnlListUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
        );

        javax.swing.GroupLayout pnlusersLayout = new javax.swing.GroupLayout(pnlusers);
        pnlusers.setLayout(pnlusersLayout);
        pnlusersLayout.setHorizontalGroup(
            pnlusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
            .addComponent(pnlListUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlusersLayout.setVerticalGroup(
            pnlusersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlusersLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlListUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPrivado.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mensajes Privados");

        txtMsgPrivados.setColumns(20);
        txtMsgPrivados.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtMsgPrivados.setRows(5);
        txtMsgPrivados.setEnabled(false);
        jScrollPane2.setViewportView(txtMsgPrivados);

        txtPrivate.setColumns(20);
        txtPrivate.setRows(3);
        jScrollPane3.setViewportView(txtPrivate);

        btnSendPrivate.setBackground(new java.awt.Color(0, 153, 255));
        btnSendPrivate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSendPrivate.setText("Enviar");

        txtUserSelec.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtUserSelec.setText("Ninguno");

        javax.swing.GroupLayout pnlPrivadoLayout = new javax.swing.GroupLayout(pnlPrivado);
        pnlPrivado.setLayout(pnlPrivadoLayout);
        pnlPrivadoLayout.setHorizontalGroup(
            pnlPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrivadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(pnlPrivadoLayout.createSequentialGroup()
                        .addGroup(pnlPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrivadoLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addComponent(btnSendPrivate))
                            .addComponent(txtUserSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlPrivadoLayout.setVerticalGroup(
            pnlPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrivadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrivadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrivadoLayout.createSequentialGroup()
                        .addComponent(btnSendPrivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMsgGrupal.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Mensages Grupales");

        txtMsgGrupo.setColumns(20);
        txtMsgGrupo.setRows(5);
        txtMsgGrupo.setEnabled(false);
        jScrollPane4.setViewportView(txtMsgGrupo);

        txtMsg.setColumns(20);
        txtMsg.setRows(3);
        jScrollPane5.setViewportView(txtMsg);

        btnSend.setBackground(new java.awt.Color(0, 102, 204));
        btnSend.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSend.setText("Enviar");

        javax.swing.GroupLayout pnlMsgGrupalLayout = new javax.swing.GroupLayout(pnlMsgGrupal);
        pnlMsgGrupal.setLayout(pnlMsgGrupalLayout);
        pnlMsgGrupalLayout.setHorizontalGroup(
            pnlMsgGrupalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMsgGrupalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMsgGrupalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(pnlMsgGrupalLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMsgGrupalLayout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend)))
                .addContainerGap())
        );
        pnlMsgGrupalLayout.setVerticalGroup(
            pnlMsgGrupalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMsgGrupalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMsgGrupalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlusers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPrivado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMsgGrupal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlusers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPrivado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMsgGrupal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMsgGrupal.getAccessibleContext().setAccessibleDescription("");
        pnlMsgGrupal.getAccessibleContext().setAccessibleParent(pnlMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPortClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortClientActionPerformed

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here:
        if(txtUserName.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Favor de elegir un nombre de usuario");
        if(txtPortClient.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Favor de elegir un puerto para el cliente");
        
        if(txtIP_Port1.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Favor Agregar la ip y el puerto del servidor IP:Puerto");
        
        if(txtServerName.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Favor Poner el nombre del servidor");
        
        try {
            StartChat();  
            pnlMain.setVisible(true);
            SetEnableHeader(false);
        } catch (Exception e) {
            txtLog.append("\n"+e.getMessage());            
            pnlMain.setVisible(false);
            SetEnableHeader(true);
        }
    }//GEN-LAST:event_btnStartMouseClicked

    private void LiUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LiUsersValueChanged
        // TODO add your handling code here:
       txtUserSelec.setText(LiUsers.getSelectedValue());
       int index = LiUsers.getSelectedIndex();
    }//GEN-LAST:event_LiUsersValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> LiUsers;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendPrivate;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblClientPort;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlListUsers;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMsgGrupal;
    private javax.swing.JPanel pnlPrivado;
    private javax.swing.JPanel pnlServer;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlusers;
    private javax.swing.JTextField txtIP_Port1;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextArea txtMsg;
    private javax.swing.JTextArea txtMsgGrupo;
    private javax.swing.JTextArea txtMsgPrivados;
    private javax.swing.JTextField txtPortClient;
    private javax.swing.JTextArea txtPrivate;
    private javax.swing.JTextField txtServerName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JLabel txtUserSelec;
    // End of variables declaration//GEN-END:variables

    private void StartChat() throws RemoteException, NotBoundException, UnknownHostException, AlreadyBoundException {
        ChatClient chat = new ChatClient();
        String[] args = txtIP_Port1.getText().split(":");
        IP = args[0];
        PORT = Integer.valueOf(args[1]);
        ClientPORT = Integer.valueOf(txtPortClient.getText());
        Registry registry = LocateRegistry.getRegistry(IP, PORT);
        SERVER = (IChatServer) registry.lookup(txtServerName.getText());  
        //Cargar lista de ususarios
        LoadListUsers();
        clServer = new ServerClient(
                ClientPORT,
                txtUserName.getText());
    }

    private void SetEnableHeader(boolean b) {
        txtUserName.setEnabled(b);
        txtPortClient.setEnabled(b);
        txtIP_Port1.setEnabled(b);
        txtServerName.setEnabled(b);
        btnStart.setEnabled(b);
    }

    private void LoadListUsers() throws RemoteException {
        String res = SERVER.Connect(txtUserName.getText(), ClientPORT);
        ListUsers = utils.Json.toArray(res);        
        ArrayList<String> model = new ArrayList<>();
        for (Client cl : ListUsers) {            
            model.add(cl.UserName + " ["+cl.IP+"]");
        }
        LiUsers.setListData(model.toArray(new String[0]));
    }
}
